### ISSUE TITLE
Problem with EventPointer_IGV function

### ISSUE THREAD

**Issue by inaae** [jpromeror/EventPointer#10]
Hi,

First of all, thank you for developing this great tool. 

I'm analyzing HTA arrays using annotation from Gencode (gencode.v19.annotation.gtf.). 
I've succeeded in generating a CDF file used to normalize the arrays and to run the EventPointer function. However, I encountered this error when executing the EventPointer_IGV function:

```
Creating SG Information...
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK

Reading Information On Probes...Done
Indexing Genes and Probes...Done
  |                                                                                                                        |   0%
Error in xj[i] : invalid subscript type 'list'
```

The function manages to generate a paths.gtf and probes.gtf file containing information for the first 11 events in the Events data.frame, however, stops when processing event number 12. 

Running a traceback returns this message:
```
traceback()
4: `[.data.frame`(SG_Edges, P1.ix, )
3: SG_Edges[P1.ix, ]
2: GetIGVPaths(EventsInfo[jj, ], SG_Edges)
1: EventPointer_IGV(Events = Events, input = "CustomGTF", inputFile = gtf_file, 
       PSR = PSRProbes, Junc = JunctionProbes, PathGTF = Directory, 
       EventsFile = EventsFound, microarray = "HTA-2_0")
```

I've used the annotation for PSRs and Junctions provided in the dropbox link, and the set up I've used to run the function is:
```
# SET INPUT VARIABLES
PathFiles <- "C:/EventPointer/Gencode_v19"

gtf_file <- paste(PathFiles,"/gencode.v19.annotation.gtf",sep="")

PSRProbes <- paste(PathFiles,"/HTA-2_0_PSR_Probes.txt",sep="")

JunctionProbes <- paste(PathFiles,"/HTA-2_0_Junc_Probes.txt",sep="")

EventsFound <- paste(PathFiles,"/Output/EventsFound_HTA-2_0.gencode.v19.txt",sep="")

Directory <- paste(PathFiles,"/Output/",sep="")

array <- "HTA-2_0"

# EXECUTE EVENTPOINTER
Events <- EventPointer(Design = Dmatrix,
                       Contrast = Cmatrix,
                       ExFit = ExFit,
                       Eventstxt = EventsFound,
                       Filter = FALSE,
                       Qn = 0.25,
                       Statistic = "LogFC",
                       PSI = TRUE)

# CREATE VISUALIZATION FILES
EventPointer_IGV(Events = Events,
                 input = 'CustomGTF',
                 inputFile = gtf_file,
                 PSR = PSRProbes,
                 Junc = JunctionProbes,
                 PathGTF = Directory,
                 EventsFile = EventsFound,
                 microarray = "HTA-2_0")
```
```
sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Norwegian (Bokmål)_Norway.1252  LC_CTYPE=Norwegian (Bokmål)_Norway.1252   
[3] LC_MONETARY=Norwegian (Bokmål)_Norway.1252 LC_NUMERIC=C                              
[5] LC_TIME=Norwegian (Bokmål)_Norway.1252    

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] aroma.light_3.12.0          aroma.affymetrix_3.1.1      affxparser_1.54.0           aroma.core_3.1.3           
 [5] R.devices_2.16.0            R.filesets_2.12.1           R.utils_2.7.0               R.oo_1.22.0                
 [9] R.methodsS3_1.7.1           limma_3.38.3                EventPointer_2.0.1          Matrix_1.2-15              
[13] SGSeq_1.16.2                SummarizedExperiment_1.12.0 DelayedArray_0.8.0          BiocParallel_1.16.5        
[17] matrixStats_0.54.0          Biobase_2.42.0              Rsamtools_1.34.1            Biostrings_2.50.2          
[21] XVector_0.22.0              GenomicRanges_1.34.0        GenomeInfoDb_1.18.1         IRanges_2.16.0             
[25] S4Vectors_0.20.1            BiocGenerics_0.28.0 
```       

I don't know if anyone has experienced the same problem, and any help will be greatly appreciated.
Thank you in advance.

**Comment by jpromeror** [comment]
Hello @inaae 

Could you show me event number 12 (the corresponding row of the data.frame)? .
Im guessing there is a bug when relating probes and/or genes to a custom annotation, such as gencode. I will run the pipeline in order to replicate the problem.

Thanks for the detailed outputs!

- Juan Pablo

**Comment by inaae** [comment]
Hi @jpromeror 

Thanks for the quick reply.

I tried to run the EventPointer_IGV function after dropping event number 12, and this time it continued to run until it hit event number 85 before stopping, returning the same type of error and traceback.

The annotation for event 12 and 85 in the Events data.frame is:
```
	Gene name	Event Type	Genomic Position	Splicing Z Value	Splicing Pvalue	Delta PSI				
ENSG00000240990.5_1	ENSG00000240990.5	Complex Event	7:27224703-27225728	-3.940596	8.12794E-05	0.11977989				
ENSG00000116521.6_11	ENSG00000116521.6	Alternative Last Exon	1:155230450-155231448	3.286953	0.001012776	-0.03581216				
```

Additionally, I observed that for at least one event in the resulting truncated paths.gtf file, there was only annotation for the "Ref1" path and no annotation for paths "A" and "B", although the probes.gtf file contained annotation for probes hitting all paths of this event. The annotation for this event in the Events data.frame is: 
```
	Gene name	Event Type	Genomic Position	Splicing Z Value	Splicing Pvalue	Delta PSI
ENSG00000046647.9_4	ENSG00000046647.9	Complex Event	X:14039630-14047896	-3.947823	7.88651E-05	0.07675793
```

The annotation for these three events in the EventsFound file is as follows:
```
Affy Gene Id	Gene Name	Event Number	Event Type	Genomic Position	Path 1	Path 2	Path Reference	Probes P1	Probes P2	Probes Ref
ENSG00000240990.5	ENSG00000240990.5	1	Complex Event	7:27224703-27225728	1-2,2-2,2-3	1-7	1-1	6480874,4953659,5101358,79123,4102256,5096575,3276903,4402657,3604019,3352205,5231529,807375,2472634,1015272	1613672,968238,5439297,1280850	6890328,2404306,4100750,4237457,2720622,4856797,6730695,2427485,2733286,1120007,3248284,6802117,4660942,2373085,1406080,1883227,6297306,3440838,4566496,4512921
ENSG00000116521.6	ENSG00000116521.6	11	Alternative Last Exon	1:155230450-155231448	12-12,12-13	11-13	13-13	2680180,6354696,3621241,740605,3967470,3410429,165163,4681225,3186123,4697975	3540550,4540860,1593579,511480	5250193,2208703,2404473,3367217,4720695,6425345,4402395,6554566,3223649,6715770
ENSG00000046647.9	ENSG00000046647.9	4	Complex Event	X:14039630-14047896	7-10	5-10	10-10	5137869,6360577,1888157,1068895	788142,4077138,4369875,1157591	1508841,5210285,491109,1249779,6406472,2303707,982633,3807502,2422427,5871859,930037,6571785,3902836,5709265,1544952,6543324,5742324,615709,6691549,2913063
```

Thanks a lot for the support!

**Comment by jpromeror** [comment]
Hi @inaae 

We have identified the source of the problem.

During one of the updates to EventPointer, some of the internal functions were modified to solve minor bugs and speed improvements. Both functions CDFfromGTF and EventPointer_IGV call a secondary function (SG_Info) that was later updated to SG_creation.

It seems that we forgot to include the update on EventPointer_IGV and this causes the problem when creating the visualisation files for some specific events.

We will update this ASAP.

Thanks for the heads up in the bug!

Best,

- Juan Pablo

**Comment by inaae** [comment]
Hi @jpromeror 

I'm glad you were able to identify the source of the problem, and that the function will be updated. Would it be possible to notify me as soon as the update is done? The truth is that I'm in bit of a hurry.

Thank you very much!

Best regards,
Ina

**Comment by jpromeror** [comment]
@inaae 

It should be fixed ASAP.
The bug will appear as corrected in the GitHub repository and we will try to propagate the fix to BioC.

I will close the issue.

Thanks!

- Juan Pablo

**Comment by johnscrn** [comment]
@inaae were you able to make this work

@jpromeror I am having what looks like the same issue with the MTA array. I started with the 2.2.4 version from BioC and then downloaded 2.3.4 from github; I have the same issue with each. 
As I remove rows the process will make it farther as the original ticket said. I too used the dropbox annotations. 

```
Events[c(10,44),]  
                        Gene name    Event Type      Genomic Position
TC0400002529.mm_5 TC0400002529.mm Complex Event   4:43518464-43519003
TC0500003178.mm_1 TC0500003178.mm Complex Event 5:120808203-120808789
                  Splicing Z Value Splicing Pvalue   Delta PSI
TC0400002529.mm_5         5.878168    4.148320e-09 -0.10117646
TC0500003178.mm_1         4.769664    1.845333e-06 -0.08787332
```

**Comment by inaae** [comment]
@johnscrn 

Yes, I was able to get the function to work after the bug fix.

**Comment by johnscrn** [comment]
thank you, I will start a new ticket then.
