### ISSUE TITLE
Error in `.rowNamesDF

### ISSUE THREAD

**Issue by KJK80** [jpromeror/EventPointer#13]
Hello,
I hope you can help, I am trying to run EventPointer on output from aroma.affy following the example in the vignette, however, when I run ;

Events<-EventPointer(Design=Design_matrix,
Contrast=Contrast_matrix,
ExFit=affy_output,
Eventstxt=EventsFound,
Filter=FALSE,
Qn=0.25,
Statistic="LogFC",
PSI=TRUE)

I get the following : 

12:16:19 Running EventPointer:  
	** Statistical Analysis: Logarithm of the fold change of both isoforms 
	** Delta PSI will be calculated 
	** No expression filter 
         ---------------------------------------------------------------- 
	** Calculating PSI...Done 
	** Running Statistical Analysis...Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed

I have looked at all the input files and tried numerous different ways of numbering any column which might be getting used as the row names to ensure no duplicates but still get this error. Any ideas on what I should try?! Thanks!

**Comment by KJK80** [comment]
Solved! It was running using the deafult files in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/EventPointer/extdata . I needed to copy the specific EventsFound.txt file for my clariomD dataset to that location!

**Comment by jpromeror** [comment]
Hi @KJK80 

Im glad you were able to solve the issue.

Just  one comment: There is no need to put the EventsFound.txt in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/EventPointer/extdata
You can specify the complete path to the file even if it is located at any other place.

Thanks for using EventPointer!
