### ISSUE TITLE
Error with EventPointer_IGV

### ISSUE THREAD

**Issue by KJK80** [jpromeror/EventPointer#14]
Hello,

I am getting the following error with EventPointer_IGV. I am running it with the ClariomD probe and gtf files you provide.

``` 
EventPointer_IGV(Events=Events,
input= "CustomGTF",
inputFile=GTF,
PSR= PSRProbes,
Junc=JunctionProbes,
PathGTF=Directory,
EventsFile= EventsFound,
microarray='ClariomD')

Creating SG Information...Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK

Reading Information On Probes...Done
Indexing Genes and Probes...Done
  |=                                                                                                   |   1%Error in xj[i] : invalid subscript type 'list'
```

It will only work if I change "Events=Events" to "Events=Events[1,,drop=FALSE]"

Thanks so much for any help you can offer!!

**Comment by KJK80** [comment]
Additionally, prior to this error I was getting this one:
```
EventPointer_IGV (Events=Events[1,,drop=FALSE],
input= "CustomGTF",
inputFile=GTF,
PSR= PSRProbes,
Junc=JunctionProbes,
PathGTF=Directory,
EventsFile= EventsFound,
microarray='ClariomD')

Creating SG Information...Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK

Reading Information On Probes...Error in .replace_seqlevels_style(x_seqlevels, value) : 
 found no sequence renaming map compatible with seqname style "UCSC" for this object

This seemed to be resolved by removing the "chr" string from the seq_name column in the Clariom_D_JunctionProbes.txt file (leaving just a number).

**Comment by jpromeror** [comment]
Hello @KJK80 

Sorry for the late answer! I changed emails recently and the notification went to the past one.

One of the things we recommend is just generating the GTF files for the events you are interested in. If you generate them all, it will be very hard to differentiate between events. I would go for something like:

```
EventPointer_IGV(Events=Events[1:5,],
input= "CustomGTF",
inputFile=GTF,
PSR= PSRProbes,
Junc=JunctionProbes,
PathGTF=Directory,
EventsFile= EventsFound,
microarray='ClariomD')
```
Still it would be interesting to know exactly which event is causing the error so we can take a look.

Regarding the second error, I will check if any default parameter has changed recently.

Thanks for pointing that out.

**Comment by KJK80** [comment]
Hi,
Thank you for the reply!

I have tried running it with just the first 2 events, but I still get the same error - 
Error in xj[i] : invalid subscript type 'list'
So it only seems to work on the first event alone. This is how my table of events looks for the first 5, I'm not sure if there is anything obviously wrong with it?
<img width="1171" alt="Screenshot 2021-06-17 at 10 16 56" src="https://user-images.githubusercontent.com/83453678/122370363-e9b4a800-cf56-11eb-8671-6080a8acb1ba.png">

Thank you so much for your help!

**Comment by JFerrer-B** [comment]
Hi,

Sorry for the late answer.

EventPointer creates the splicing graph twice for the arrays version of EventPointer. The first time in the CDFfromGTF function and the second time when calculating the GTF of the events.

The files that are in the dropbox were created with a former version of the internal function that creates the splicng graph. This function has been improved.

If the dropbox data is used, the same version of this internal function should be used when calling the EventPointer_IGV function.

Therefore, we have to update the dropbox data to avoid future problems.

In the meantime, so you don't have to wait, this problem could be solved in two different ways:

1) In the EventPointer_IGV function,  uncomment line 387 and add a comment 388:

now:
line 387:  #SG_Edges <- SG_Info (SG_Gene) $ Edges
line 388:  SG_Edges <- SG_creation_RNASeq (SG_Gene) $ Edges

to fix it:
line 387:  SG_Edges <- SG_Info (SG_Gene) $ Edges
line 388:  #SG_Edges <- SG_creation_RNASeq (SG_Gene) $ Edges


SG_info is the old version of the internal function that generates the SG  and SG_creation_RNASeq is the new version.

2) the other option is to execute the CDFfromGTF function and generate the files again.

Hope that way you can solve the problem. If this is not the case, I will be happy to help you.

Juan

**Comment by KJK80** [comment]
Hi,
I re-created the files using CDFfromGTF and it seems to be working ok now!
Thank you so much! :-)
