### ISSUE TITLE
Flipping Cmatrix leads to wrong deltaPSIs

### ISSUE THREAD

**Issue by rtasakis** [jpromeror/EventPointer#21]
I have noticed than when flipping the Cmatrix from `Cmatrix<-t(t(c(0,1)))` to `Cmatrix<-t(t(c(1,0)))` the deltaPSI values completely change and lead to only positive deltaPSIs.

**Following the default documentation**
```
Cmatrix<-t(t(c(0,1))) 
Dmatrix<-matrix(c(rep(1, times=8), rep(c(0,1), each=4)), ncol=2, byrow=FALSE) 
Events <- EventPointer_RNASeq(AllEvents_RNASeq, Dmatrix, Cmatrix, Statistic="LogFC",PSI=TRUE)
```
I obtain the same values as in the [documentation](https://bioconductor.org/packages/release/bioc/vignettes/EventPointer/inst/doc/EventPointer.html#rna-seq-analysis).

**Flipped Cmatrix**
```
Cmatrix<-t(t(c(1,0))) 
Dmatrix<-matrix(c(rep(1, times=8), rep(c(0,1), each=4)), ncol=2, byrow=FALSE) 
Events <- EventPointer_RNASeq(AllEvents_RNASeq, Dmatrix, Cmatrix, Statistic="LogFC",PSI=TRUE)
```
![Screenshot 2023-09-05 at 12 17 46 PM](https://github.com/jpromeror/EventPointer/assets/32274562/5f9529f2-1c9f-4bc5-a1ca-8b3dfd7198c2)

I would expect that by flipping the Cmatrix (aka change the contrast and base levels of bam files) the absolute deltaPSI would remain the same, while + values would become - and the opposite. I would need to know why this happens, because in a different dataset the contrast-level and base-level bams are organized in the opposite direction than the default indicated in the bioconductor documentation and it reported wrong deltaPSIs. Can you explain why this happens? Thanks in advance!

**Comment by JFerrer-B** [comment]
Hello Rafail,
Although it may seem intuitive that the deltaPSI should remain the same and change sign, this is not the case.

Notice that in the design matrix, there is an intercept: all elements in the first column are 1. With this design matrix, the coefficients obtained when creating a linear model (which is what EP does internally) are:

beta_0 = the mean of the control values.
beta_1 = the difference between the cases' and the control's mean.

Considering the interpretation of these coefficients, the contrast matrix should be
[0 1]. This is equivalent to testing the following null hypothesis:

beta_1 = 0 
which is the same that:
mean(PSI_case) - mean(PSI_control)

A contrast matrix of [1 0] will test if:

beta_0 = 0
which is the same that:
mean(PSI_control) = 0


Juan
