### ISSUE TITLE
getPSI function

### ISSUE THREAD

**Issue by hershbc** [jpromeror/EventPointer#3]

**Comment by jpromeror** [comment]
@hershbc 

The function should work properly. First let's be sure you have the updated versions of the algorithm.

The R version that should be installed is R 3.4 and EventPointer 1.0.0
Once that is checked, run the following lines:

```{r}
EventPointer:::getPSI
```
This should display the R code fot the getPSI function. 

Finally, if the problem persists try to reinstall the package from bioconductor:

```{r}
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
biocLite("EventPointer")
```

Let me know if there is any problem.

**Comment by hershbc** [comment]
Hi, Thanks for responding even though I deleted the comment. Re-installing solved the problem.  I think the issue was that I upgraded to R 3.4 during the same session as trying to install Event Pointer and it caused problems.  I haven't gotten it to run all the way through yet, it doesn't seem to like my Design and Contrast matrices, but I'm further than I was Monday.  Thank you.

**Comment by hershbc** [comment]
Well, maybe you can tell me what looks wrong here.  

> Design
  (Intercept) TreatLUC7L2OE TreatshLUC7L2
1           1             0             0
2           1             0             0
3           1             0             0
4           1             1             0
5           1             1             0
6           1             1             0
7           1             0             1
8           1             0             1
9           1             0             1
attr(,"assign")
[1] 0 1 1
attr(,"contrasts")
attr(,"contrasts")$Treat
[1] "contr.treatment"

> Contrast
[1]  0 -1  1

**Comment by jpromeror** [comment]
Contrast must be a column vector.

Try with this:

```{r}
Contrast<-t(t(c(0,-1,1)))
```
> Contrast
     [,1]
[1,]    0
[2,]   -1
[3,]    1

Let me know if there is any other problem.

**Comment by jpromeror** [comment]
Hi @hershbc 

Is the problem solved?

Please let me know so I can close this issue.

Best regards

**Comment by hershbc** [comment]
Thank you! That was a big help!  I've been able to create the Events object and now I'm working on  making the IGV files.
