### ISSUE TITLE
Error in making TxDb object from Bioconductor

### ISSUE THREAD

**Issue by binasu** [jpromeror/EventPointer#9]
Hi,

Thanks for this great tool!

I encountered this error in my EventPointer execution (which I'm running in Unix):

Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... Error in .make_splicings(exons, cds, stop_codons) :
  some CDS cannot be mapped to an exon
Calls: PrepareBam_EP ... makeTxDbFromGFF -> makeTxDbFromGRanges -> .make_splicings
Execution halted

I generated the BAM files with STAR and I'm using the C. elegans WS251 GTF file.

Thanks,
Bina

**Comment by jpromeror** [comment]
Hi @binasu,

Sorry for the delay in the answer! 

I've never worked with sequencing files from species different than human, mouse or pig. Can you tell me where you downloaded the GTF file? I will try to replicate the issue.

By the error message it seems that is coming from SGSeq when building the splicing graph.

I'll let you know as soon as I have updates.

Best regards,

- Juan Pablo

**Comment by jpromeror** [comment]
Hello @binasu,

I will close the issue as there has been no response or comment since July.

Best,

- Juan Pablo

**Comment by jadeeerose** [comment]
Were you able to resolve this? I am getting the same error using a bacterial genome.
